name: able
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - openssl=3.0.15
  - python=3.11.9
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - certifi==2024.8.30
      - click==8.1.7
      - colorama==0.4.6
      - decorator==5.1.1
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.115.4
      - fastapi-cli==0.0.5
      - filelock==3.13.1
      - fsspec==2024.2.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx==0.27.2
      - idna==3.10
      - jinja2==3.1.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - opencv-python==4.10.0.84
      - pillow==10.2.0
      - pip==24.3.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.16
      - pyyaml==6.0.2
      - rich==13.9.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.41.2
      - sympy==1.13.1
      - typer==0.12.5
      - typing-extensions==4.12.2
      - uvicorn==0.32.0
      - watchfiles==0.24.0
      - websockets==13.1